# Copyright (c) 2024-2025, Personal Robotics Laboratory
# License: BSD 3-Clause. See LICENSE.md file in root directory.

---
imu_jointstate_publisher:
  ros__parameters:
    joint_name: 'robot_tilt'
    main_calib_vector: # [X, Y, Z]
      - -1003.4183333333335
      - -24.198333333333334
      - 38.275000000000006

    tilt_calib_vector: # [X, Y, Z]
      - -978.8416666666667
      - -232.50333333333336
      - 40.96

    serial_port: '/dev/ttyUSB1'
    velocity_thresh: 0.05 # radians per second

    # weights used in exponential rolling averages, between 0 and 1
    position_smoothing_factor: 0.1
    velocity_smoothing_factor: 0.1
