# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    jaco_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    jaco_arm_servo_controller:
      type: position_controllers/JointGroupPositionController


    hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

jaco_arm_controller:
  ros__parameters:
    joints:
      - j2n6s200_joint_1
      - j2n6s200_joint_2
      - j2n6s200_joint_3
      - j2n6s200_joint_4
      - j2n6s200_joint_5
      - j2n6s200_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_partial_joints_goal: false
    open_loop_control: false
    stopped_velocity_tolerance: 0.01
    # No gains on position interface
    j2n6s200_joint_1:
      goal: 0.02
      trajectory: 0.05
    j2n6s200_joint_2:
      goal: 0.02
      trajectory: 0.05
    j2n6s200_joint_3:
      goal: 0.02
      trajectory: 0.05
    j2n6s200_joint_4:
      goal: 0.02
      trajectory: 0.05
    j2n6s200_joint_5:
      goal: 0.02
      trajectory: 0.05
    j2n6s200_joint_6:
      goal: 0.02
      trajectory: 0.05

jaco_arm_servo_controller:
  ros__parameters:
    joints:
      - j2n6s200_joint_1
      - j2n6s200_joint_2
      - j2n6s200_joint_3
      - j2n6s200_joint_4
      - j2n6s200_joint_5
      - j2n6s200_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_partial_joints_goal: false
    open_loop_control: false
    stopped_velocity_tolerance: 0.01
    # No gains on position interface
    j2n6s200_joint_1:
      goal: 0.02
      trajectory: 0.05
    j2n6s200_joint_2:
      goal: 0.02
      trajectory: 0.05
    j2n6s200_joint_3:
      goal: 0.02
      trajectory: 0.05
    j2n6s200_joint_4:
      goal: 0.02
      trajectory: 0.05
    j2n6s200_joint_5:
      goal: 0.02
      trajectory: 0.05
    j2n6s200_joint_6:
      goal: 0.02
      trajectory: 0.05

hand_controller:
  ros__parameters:
    joints:
      - j2n6s200_joint_finger_1
      - j2n6s200_joint_finger_2
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_partial_joints_goal: false
    open_loop_control: false
    constraints:
      stopped_velocity_tolerance: 0.01
    gains: # Required because we're controlling a velocity interface
      j2n6s200_joint_finger_1: {p: 1.0,  d: 0.0, i: 0.0, i_clamp: 1.0}
      j2n6s200_joint_finger_2: {p: 1.0,  d: 0.0, i: 0.0, i_clamp: 1.0}
